[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pycvt"
version = "0.0.1-202606050005"
authors = [
  { name = "ferretsprite", email = "ferret-sprite-goon@duck.com" }
]

description = "pycvt is a Python package designed for computer vision utilities, including YOLO annotation handling, image manipulation, bounding box plotting, and data conversion tools."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "imageio>=2.37.0",
    "numpy>=1.26.0",
    "opencv-python>=4.12.0.88",
    "PyYAML>=6.0.2",
    "Pillow>=11.2.1",
    "distinctipy>=1.3.4",
    "easyfont>=0.0.1.post10",
]

[project.optional-dependencies]
yolo-predict = [
    "click>=8.1.0",
    "cvmd",
    "ray>=2.55.1",
    "torch",
    "torchvision",
]

[project.scripts]
pycvt-yolo-predict = "pycvt.tools.yolo_predict:main"
yolo-pred = "pycvt.tools.yolo_predict:main"

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true

[project.urls]
Homepage = "https://github.com/xx025"
Repository = "https://github.com/"
Documentation = "https://github.com/"

[tool.uv]
index-url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple/"

[dependency-groups]
dev = [
    "imageio>=2.37.0",
    "matplotlib>=3.10.8",
    "opencv-python>=4.12.0.88",
    "pillow>=11.2.1",
    "pydantic>=2.12.5",
    "scikit-image>=0.25.2",
]
