name: Publish to PyPI

on:
  release:
    types: [published]  # 触发时机：点击 GitHub 的发布按钮

jobs:
  publish:
    name: Build and publish using uv
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write  # 必须开启以使用 OIDC 信任认证

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Build the package
        run: |
          uv sync
          uv build

      - name: Publish to PyPI
        run: uv publish